# Generated by Django 3.0.4 on 2020-03-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_remove_quiz_time_to_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
