# Generated by Django 3.0.4 on 2020-03-12 21:01

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_auto_20200312_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='time_taken',
            field=models.DurationField(default=datetime.timedelta(500)),
            preserve_default=False,
        ),
    ]
