# Generated by Django 3.0.6 on 2020-05-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_choice_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='This is the description of the pre-existing quizzes created'),
            preserve_default=False,
        ),
    ]
