# Generated by Django 3.0.6 on 2020-05-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_quiz_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('date',)},
        ),
    ]
