# Generated by Django 3.0.6 on 2020-05-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_auto_20200526_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='score',
            field=models.FloatField(),
        ),
    ]
