# Generated by Django 3.0.6 on 2020-05-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0010_auto_20200526_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='Solution',
            new_name='solution',
        ),
    ]
