# Generated by Django 3.0.6 on 2020-05-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0011_auto_20200526_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='score',
            field=models.FloatField(),
        ),
    ]
